"""Initial migration: developers, api_keys, billing_transactions, provider_records, trust_edges

Revision ID: 3e4cc8b80ac7
Revises: 
Create Date: 2026-07-03 20:29:06.270260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from datetime import datetime, timezone


# revision identifiers, used by Alembic.
revision: str = '3e4cc8b80ac7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'developers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('balance_usdc', sa.Float(), nullable=False, server_default='0.0'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_developers_email'), 'developers', ['email'], unique=True)
    op.create_index(op.f('ix_developers_id'), 'developers', ['id'], unique=False)

    op.create_table(
        'api_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('developer_id', sa.Integer(), nullable=False),
        sa.Column('key_prefix', sa.String(), nullable=False),
        sa.Column('hashed_key', sa.String(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'),
        sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('hashed_key')
    )
    op.create_index(op.f('ix_api_keys_hashed_key'), 'api_keys', ['hashed_key'], unique=True)
    op.create_index(op.f('ix_api_keys_id'), 'api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)

    op.create_table(
        'billing_transactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('developer_id', sa.Integer(), nullable=False),
        sa.Column('amount_usdc', sa.Float(), nullable=False),
        sa.Column('balance_after', sa.Float(), nullable=False),
        sa.Column('transaction_type', sa.String(), nullable=False),
        sa.Column('endpoint', sa.String(), nullable=True),
        sa.Column('provider_id', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.ForeignKeyConstraint(['developer_id'], ['developers.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_transactions_id'), 'billing_transactions', ['id'], unique=False)

    op.create_table(
        'provider_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('provider_id', sa.String(), nullable=False),
        sa.Column('completed_jobs', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('failed_jobs', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('total_jobs', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('cusum_state', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('ema_default_rate', sa.Float(), nullable=False, server_default='0.0'),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('provider_id')
    )
    op.create_index(op.f('ix_provider_records_provider_id'), 'provider_records', ['provider_id'], unique=True)

    op.create_table(
        'trust_edges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('source_id', sa.String(), nullable=False),
        sa.Column('target_id', sa.String(), nullable=False),
        sa.Column('weight', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('source_id', 'target_id', name='uq_trust_edge')
    )
    op.create_index(op.f('ix_trust_edges_source_id'), 'trust_edges', ['source_id'], unique=False)
    op.create_index(op.f('ix_trust_edges_target_id'), 'trust_edges', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trust_edges_target_id'), table_name='trust_edges')
    op.drop_index(op.f('ix_trust_edges_source_id'), table_name='trust_edges')
    op.drop_table('trust_edges')
    op.drop_index(op.f('ix_provider_records_provider_id'), table_name='provider_records')
    op.drop_table('provider_records')
    op.drop_index(op.f('ix_billing_transactions_id'), table_name='billing_transactions')
    op.drop_table('billing_transactions')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_hashed_key'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_developers_id'), table_name='developers')
    op.drop_index(op.f('ix_developers_email'), table_name='developers')
    op.drop_table('developers')
    # ### end Alembic commands ###