"""Add event_records table for deduplication

Revision ID: 8a69eff76181
Revises: 3e4cc8b80ac7
Create Date: 2026-07-03 20:36:32.862121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a69eff76181'
down_revision: Union[str, None] = '3e4cc8b80ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('buyer_id', sa.String(), nullable=False),
    sa.Column('reporter_id', sa.String(), nullable=False),
    sa.Column('capability', sa.String(), nullable=True),
    sa.Column('price_usdc', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_records_buyer_id'), 'event_records', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_event_records_id'), 'event_records', ['id'], unique=False)
    op.create_index(op.f('ix_event_records_job_id'), 'event_records', ['job_id'], unique=True)
    op.create_index(op.f('ix_event_records_provider_id'), 'event_records', ['provider_id'], unique=False)
    op.create_index(op.f('ix_event_records_reporter_id'), 'event_records', ['reporter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_records_reporter_id'), table_name='event_records')
    op.drop_index(op.f('ix_event_records_provider_id'), table_name='event_records')
    op.drop_index(op.f('ix_event_records_job_id'), table_name='event_records')
    op.drop_index(op.f('ix_event_records_id'), table_name='event_records')
    op.drop_index(op.f('ix_event_records_buyer_id'), table_name='event_records')
    op.drop_table('event_records')
    # ### end Alembic commands ###